language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  # install dependencies from setup.py
  - pip install -e .
  - pip install coverage
  # - pip install selenium
script:
  # command to run tests
  # - python -m unittest discover -t . -s test -v
  # - python test/
  - coverage run test/
  - coverage report
addons:
  sauce_connect: true
