language: python
cache: pip
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
addons:
  chrome: stable
  firefox: latest
env:
  global:
    - MOZ_HEADLESS=1
install:
  # install dependencies from setup.py (there are none for remi)
  - pip install -e .
  # install optional packages (for linting, coverage, browser control)
  # and dependencies of example apps being tested
  - pip install flake8 coverage matplotlib Pillow selenium
  # install specific webdrivers for selenium
  - ./test/install_webdrivers
  - export PATH="$HOME/.local/bin:$PATH"
before_script:
  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
  # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
script:
  # this "coverage" command is equivalent to running `python test/`
  - coverage run test/
after_script:
  - coverage report --include="examples/*,test/*"
  - coverage report --include="remi/*,editor/*"
